### ISSUE TITLE
Sponsors images are not displaying.

### ISSUE THREAD

**Issue by yashhere** [fosscell/2017#20] opened 2016-09-21 19:05 UTC
![capture](https://cloud.githubusercontent.com/assets/13733968/18725073/6af69a80-805c-11e6-8dbe-f292e3a58a0f.JPG)

**Comment by SpEcHiDe** [comment] 2016-09-22 04:35
@fosscell/web2017 any ideas?

**Comment by SpEcHiDe** [comment] 2016-09-27 13:37
temporary FIX! so closing this for now!

**Comment by amaljose96** [comment] 2016-09-28 16:51
Set width and height manually in css

**Comment by SpEcHiDe** [comment] 2016-09-28 17:01
![screenshot from 2016-09-28 22-27-43](https://cloud.githubusercontent.com/assets/6317196/18923769/443c6108-85cb-11e6-8189-e73df2774ce9.png)

I think it is because some JavaScript resource that is being used is dynamically appending a <style> in the <head>

**Comment by SpEcHiDe** [comment] 2016-09-28 17:47
The issue is not solved. Apparently, only @yash2696 will know how to solve it!

**Comment by SpEcHiDe** [comment] 2016-10-03 08:23
turns out that it was an issue with the [adblock extension](https://github.com/chrisaljoudi/uBlock/issues/161)

**Comment by yashhere** [comment] 2016-10-03 11:17
I thought that this extension only blocks the font awesome social media icons.

**Closed as not planned** 2023-07-26 16:28 UTC
